### PR TITLE
get the serializers 'idKey' field as the cache key

### LINKED ISSUE #104: [BUG] recurseRelators fails to serialize more than one entity of a model where id field is not called "id"
## Describe the bug<sup>\*</sup>

Using [Zenstack](https://github.com/zenstackhq/zenstack) some `includes` are not included in the response as documented in this [ticket](https://github.com/zenstackhq/zenstack/issues/2264).

## To Reproduce<sup>\*</sup>

Still working on identifying a pattern since it affects only some relations but not others.

## Expected behavior<sup>\*</sup>

All entities included in the `data` for entity types in `includes` are also featured in `included` in the serialized JSON.

## Screenshots

n/a

## Platform<sup>\*</sup>

- [ ] OS: Linux / OSX
- [ ] Browser n/a
- [ ] Version: v1.12.0

## Additional context

I have debugged this and I believe the issue is in this call:
https://github.com/mathematic-inc/ts-japi/blob/main/src/classes/serializer.ts#L312

ie. in the code for `recurseRelators`:
https://github.com/mathematic-inc/ts-japi/blob/main/src/utils/serializer.utils.ts#L5

Unfortunately, VSCode crashes when I try to debug this using the step by step debugger.

### PR DESCRIPTION
**Pull request by lsmith77**
instead of hardcoding `id` as the field name

fixes #104

### CODE REVIEW

**Comment by stevendonorlink** [comment]
This fix works for me too.

**Comment by jrandolf** [comment]
Needs formatting

File: src/classes/serializer.ts [hunk 1]
```diff
@@ -80,6 +80,13 @@ export default class Serializer<PrimaryType extends Dictionary<any> = any> {
     this.collectionName = collectionName;
   }
 
+  /**
+   * Gets the idKey (ie. name of the id field for the given model)
+   */
+  public getIdKeyFieldName() {
```
Comment (lsmith77) [inline src/classes/serializer.ts:86]: is this method name consistent with internal naming conventions? should I just call it `getIdKeyName()`?

File: src/utils/serializer.utils.ts [hunk 2]
```diff
@@ -115,7 +115,7 @@ export async function recurseRelators(
         // - includeFields !== undefined
         // - includeFields has entry where field = relatedName
         if (!includeFields || includeFields.map((i) => i.field).includes(relator.relatedName)) {
-          const key = `${relator.serializer.collectionName}:${cache[i].id as string}`;
+          const key = `${relator.serializer.collectionName}:${cache[i][relator.serializer.getIdKeyFieldName()] as string}`;
```
Comment (lsmith77) [inline src/utils/serializer.utils.ts]: @jrandolf when you say needs formatting, do you mean breaking up this line?

should I introduce a `const $cacheKey = ..` ?

**Comment by lsmith77** [comment]
@jrandolf something seems to have gone wrong in your email response to my questions.

```
diff --git a/src/utils/serializer.utils.ts b/src/utils/serializer.utils.ts
index 20fe5d0..bf920c7 100644
--- a/src/utils/serializer.utils.ts
+++ b/src/utils/serializer.utils.ts
@@ -115,7 +115,10 @@ export async function recurseRelators(
         // - includeFields !== undefined
         // - includeFields has entry where field = relatedName
         if (!includeFields || includeFields.map((i) => i.field).includes(relator.relatedName)) {
-          const key = `${relator.serializer.collectionName}:${cache[i][relator.serializer.getIdKeyFieldName()] as string}`;
+          const collectionName = relator.serializer.collectionName;
+          const idKeyFieldName = relator.serializer.getIdKeyFieldName();
+          const idValue = cache[i][idKeyFieldName] as string;
+          const key = `${collectionName}:${idValue}`;
           if (!keys.includes(key)) {
             // const key = resource.getKey();
             const resource = await relator.getRelatedResource(
```

**Comment by jrandolf** [comment]
CI is not passing

**Comment by lsmith77** [comment]
Ah ok got it. Since the fix was fairly trivial, I didn't run `npm i` and so all the toolchain stuff didn't run. Hope its fixed now.

Note it would be nice to add a CONTRIBUTOR.md file, to prevent such issues for other first time contributors.

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

**Review by jrandolf — APPROVED** [review]

**Comment by jrandolf** [comment]
Thank you for your contribution.

**Comment by lsmith77** [comment]
just so that I can plan on my side if I need to do a workaround .. how soon can I expect a release with this fix?

**Comment by lsmith77** [comment]
@jrandolf I hope the small donation I just send you allows you to prioritize making a release that includes this fix in the near future. thanks!
